.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KERNELOOPS 8 "Dec 5, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kerneloops \- program to collect and submit kernel oopses to kerneloops.org
.SH SYNOPSIS
.B kerneloops
.SH DESCRIPTION
This manual page documents briefly the
.B kerneloops
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBkerneloops\fP is a program that collects kernel crash information
and then submits the extracted signature to the kerneloops.org website
for statistical analysis and presentation to the Linux kernel developers.
.br
.SH OPTIONS
.LP
 
.TP
\fB\-\-debug\fR
Enable debug mode
.TP
\fB\-\-nodaemon\fR
Do not daemonize
.SH FILES
/etc/kerneloops.conf
.SH AUTHOR
kerneloops was written by Arjan van de Ven <arjan@linux.intel.com>.
.PP
